name: Fetch LinkedIn Jobs

on:
  push:
    branches: ["main", "master", "feat/test-1"]
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  fetch-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Fetch Jobs
        run: node scripts/fetch-linkedin-jobs.js
      
      - name: Commit Saved Jobs (Pre-Geocode)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "chore: update job listings [skip ci]"
            file_pattern: public/jobs.json
      
      - name: Geocode Jobs
        run: node scripts/geocode-jobs.js

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update jobs list [skip ci]"
          file_pattern: public/jobs.json public/location-cache.json
